services:
  blog:
    image: ghost:5-alpine
    container_name: mon_blog
    restart: always
    environment:
      url: https://julestristan.fr
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost.db
      database__useNullAsDefault: "true"
      NODE_ENV: production
    volumes:
      - ./content:/var/lib/ghost/content
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog.rule=Host(`julestristan.fr`)"
      - "traefik.http.routers.blog.entrypoints=websecure"
      - "traefik.http.routers.blog.tls.certresolver=myresolver"
      - "traefik.http.services.blog.loadbalancer.server.port=2368"

networks:
  web:
    external: true